language: python
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=pypy3
install:
  - pip install tox coveralls
script:
  - tox
after_success:
  - coveralls
deploy:
  provider: pypi
  user: themattrix
  distributions: sdist bdist_wheel
  on:
    condition: $TOXENV == py27
    tags: true
    all_branches: true
    repo: themattrix/python-pystrap
  password:
    secure: 4wnKsIM7SnDSEPufBWEJ3GByUJEHmjGpX19WNCmMStcSCYVfY7PRHghm8LKkpiJJT6591VQq2XQMVaqltVUiSHA+yX1mAyoUgdjGndT6o/CevfQSJZv+eMpmeBn5TWn0xCkH9nAOISfwk+SIyxd8tnCSalUKBtDqHRWVwW/Wre+b902PHFgKBcsUJeYOt0EQyaGV8mKN/zFPDvu5QcNfCOwOIl1yq23Uqwgin4nucbLu70r7LTC4itol5FsldQ+HVtu/Yz84Ol6knaZGyfM8l5ehLFLiY2EwM0XPyDzkuCruCxN0MUccDGDhCgU2kYrMJBUJEnMmAa6AxVVwbOPTuosfPtWF4M68u4b2ybtT0ZqqcFH7BEnsz92CK7TrZVN92pb+EJY/lFAcWnLEOTXtk/FMrzvYPKAPG//fjt29+fRLGZmg/vkmLTR/498dQ8P6CSmSXsHH7y/YwQ3JLGfWD3r9WVKhqKav3nHDrTxLKwLBOogVVU4VGBCNnOMZ9XN+6JMvhbNDBJ2nADK1C3QXwl7AA7cSfHkfUQHMbeCiH5E9FwMKMcdv91SpIMn27KurwmDjH3t2Ar4hl1eKoWv/y9gxJ345hncseyRSz5V50Mx5ZG97XK2PhfH3+wkBwbQif4HJXQDGypOrNkWEFTslKHa+RVUL3/HcSXk35pfnlPY=
